version: "3"
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - qdrant_network

  fastapi:
    build:
      context: .
    ports:
      - "8080:8000"
    networks:
      - qdrant_network

volumes:
  qdrant_data:

networks:
  qdrant_network:
